// RARA AI - MULTI DEVICE, AIZAT, MADE IN INDONESIA
import { getAssetBuffer } from "../../src/lib/rara-asset-manager.js";
import { prepareWAMessageMedia, generateWAMessageFromContent, proto } from "rara";
import { raraError, raraEmpty, raraGuide, raraNoInput, raraWrap } from "../../src/lib/rara-menu-style.js";
import { buildServerDescription } from "../../src/lib/panel/description.js";
import { isLocationMismatchError, buildLocationMismatchHelp } from "../../src/lib/panel/locations.js";
import axios from 'axios'
import crypto from 'crypto'
import config from '../../config.js'
import { isLid, lidToJid } from '../../src/lib/rara-lid.js'
import { checkPanelJeda, setPanelLastUsed } from '../../src/lib/rara-panel-jeda.js'
import { hasAccessToServer, getUserRole, VALID_SERVERS } from '../../src/lib/rara-roles-cpanel.js'
import { isGcSeller } from './gcseller.js'
import * as timeHelper from '../../src/lib/rara-time.js'
import { getDatabase } from '../../src/lib/rara-database.js'

const pluginConfig = {
  name: 'cp',
  alias: ["cp"],
  category: 'panel',
  description: 'Create panel custom (RAM, disk, CPU, nomor target)',
  usage: '.cp <ram> <disk> <cpu> <nomor>\n.contoh: .cp 1gb 1gb 100 628xxx',
  example: '.cp 2gb 2gb 100 628311880113',
  isOwner: false,
  isPremium: false,
  isGroup: false,
  isPrivate: false,
  cooldown: 10,
  energi: 0,
  isEnabled: true,
}

// Parse RAM/disk value: "1gb" -> 1024, "unli" -> 0, "512mb" -> 512
function parseMemory(val) {
  if (!val) return null
  val = val.toLowerCase().trim()
  if (val === 'unli' || val === 'unlimited' || val === '0') return 0
  const gbMatch = val.match(/^(\d+)gb$/)
  if (gbMatch) return parseInt(gbMatch[1]) * 1024
  const mbMatch = val.match(/^(\d+)mb$/)
  if (mbMatch) return parseInt(mbMatch[1])
  const numMatch = val.match(/^(\d+)$/)
  if (numMatch) return parseInt(numMatch[1])
  return null
}

// Parse CPU: "100" -> 100, "unli" -> 0 (unlimited)
function parseCpu(val) {
  if (!val) return null
  val = val.toString().toLowerCase().trim()
  if (val === 'unli' || val === 'unlimited' || val === '0') return 0
  const num = parseInt(val.replace(/[^0-9]/g, ''))
  if (isNaN(num) || num < 1 || num > 400) return null
  return num
}

// Clean phone number
function cleanNumber(val) {
  if (!val) return null
  let num = val.toString().replace(/[^0-9]/g, '')
  if (num.startsWith('0')) num = '62' + num.slice(1)
  if (!num.startsWith('62')) num = '62' + num
  return num + '@s.whatsapp.net'
}

function cleanJid(jid) {
  if (!jid) return null
  if (isLid(jid)) jid = lidToJid(jid)
  return jid.includes("@") ? jid : jid + "@s.whatsapp.net"
}

function capitalize(str) {
  return str.charAt(0).toUpperCase() + str.slice(1).toLowerCase()
}

function formatDate() {
  return timeHelper.formatDateTime("D MMMM YYYY HH:mm")
}

function getServerConfig(pteroConfig, serverKey) {
  const num = parseInt(String(serverKey || "").replace("s", ""), 10)
  if (!(num >= 1 && num <= 100)) return null
  return pteroConfig["server" + num] || null
}

function validateServerConfig(serverConfig) {
  const missing = []
  if (!serverConfig?.domain) missing.push("domain")
  if (!serverConfig?.apikey) missing.push("apikey (PTLA)")
  return missing
}

function getAvailableServers(pteroConfig) {
  const available = []
  for (let i = 1; i <= 100; i++) {
    const cfg = pteroConfig?.[`server${i}`]
    if (cfg?.domain && cfg?.apikey) available.push(`v${i}`)
  }
  return available
}

// Auto-generate ptlc_ (Client API Key)
async function generateClientApiKey(domain, email, password) {
  try {
    const loginRes = await axios.post(
      `${domain}/api/auth/login`,
      { email, password },
      { headers: { "Content-Type": "application/json", "Accept": "application/json" }, timeout: 10000 }
    )
    const authToken = loginRes.data?.token || loginRes.data?.data?.token
    if (!authToken) return null

    const keyRes = await axios.post(
      `${domain}/api/client/account/api-keys`,
      { description: "Auto-generated by Rara Bot", allowed_ips: [] },
      { headers: { Authorization: `Bearer ${authToken}`, "Content-Type": "application/json", "Accept": "application/json" }, timeout: 10000 }
    )
    return keyRes.data?.secret || keyRes.data?.data?.secret || null
  } catch (e) {
    console.log("[Rara Panel] Auto-generate ptlc_ failed:", e?.response?.status || e.message)
    return null
  }
}

async function handler(m, { sock }) {
  const pteroConfig = config.pterodactyl
  const prefix = m.prefix || '.'
  const text = (m.text || '').trim()

  if (!text) {
    return m.reply(
      raraWrap("Panel", `CARA PAKAI CUSTOM PANEL\n\n` +
      `Format:\n` +
      `${prefix}cp <ram> <disk> <cpu> <nomor>\n\n` +
      `Contoh:\n` +
      `${prefix}cp 1gb 1gb 100 628311880113\n` +
      `${prefix}cp 2gb 5gb 150 628xxx\n` +
      `${prefix}cp unli unli 200 628xxx\n\n` +
      `Parameter:\n` +
      `  ram = RAM server (1gb, 2gb, unli)\n` +
      `  disk = Penyimpanan (1gb, 5gb, unli)\n` +
      `  cpu = CPU limit (1-400) atau unli\n` +
      `  nomor = Nomor WhatsApp target\n\n` +
      `Server tersedia: ${getAvailableServers(pteroConfig).join(', ') || 'none'}`, "guide"),
      "Panel"
    )
  }

  // Parse args: bisa spasi atau koma
  // Format: .cp 1gb 1gb 100 628xxx
  // Atau:   .cp 1gb 1gb 100,628xxx
  let parts = text.replace(/,/g, ' ').split(/\s+/).filter(Boolean)

  // Optional: server version di awal (v1-v100)
  let serverVersion = 'v1'
  let serverKey = 's1'
  if (parts[0] && /^v(\d{1,3})$/i.test(parts[0])) {
    const verNum = parseInt(parts[0].replace(/^v/i, ''), 10)
    if (verNum >= 1 && verNum <= 100) {
      serverVersion = 'v' + verNum
      serverKey = 's' + verNum
    }
    parts = parts.slice(1)
  }

  const ramInput = parts[0]
  const diskInput = parts[1]
  const cpuInput = parts[2]
  const usernameInput = parts[3]
  const numberInput = parts[4]

  if (!ramInput || !diskInput || !cpuInput || !usernameInput || !numberInput) {
    return m.reply(raraWrap("Panel",
      `Format tidak lengkap\n\n` +
      `Gunakan: ${prefix}cp <ram> <disk> <cpu> <nomor>\n` +
      `Contoh: ${prefix}cp 1gb 1gb 100 628311880113`
    ))
  }

  const ramMb = parseMemory(ramInput)
  const diskMb = parseMemory(diskInput)
  const cpu = parseCpu(cpuInput)

  if (ramMb === null) {
    return m.reply(raraWrap("Panel", `RAM tidak valid: ${ramInput}\nGunakan format: 1gb, 512mb, unli`))
  }
  if (diskMb === null) {
    return m.reply(raraWrap("Panel", `Disk tidak valid: ${diskInput}\nGunakan format: 1gb, 512mb, unli`))
  }
  if (cpu === null) {
    return m.reply(raraWrap("Panel", `CPU tidak valid: ${cpuInput}\nGunakan angka 1-400 (persen)`))
  }

  // Determine target user
  let targetUser = cleanNumber(numberInput)
  if (!targetUser) {
    if (m.quoted?.sender) {
      targetUser = cleanJid(m.quoted.sender)
    } else if (m.mentionedJid?.length > 0) {
      targetUser = cleanJid(m.mentionedJid[0])
    } else {
      targetUser = cleanJid(m.sender)
    }
  }

  if (!targetUser) {
    return m.reply(raraWrap("Panel", `Tidak dapat menentukan nomor target.`))
  }

  // Validate WhatsApp number
  const isPlatformUser = /^(tg|dc)_/.test(String(targetUser.split("@")[0])); // bridge: user TG/Discord bukan nomor WA
  try {
    const [onWa] = isPlatformUser ? [{ exists: true }] : await sock.onWhatsApp(targetUser.split("@")[0])
    if (!onWa?.exists) {
      return m.reply(raraWrap("Panel", `Nomor ${targetUser.split("@")[0]} tidak terdaftar di WhatsApp!`))
    }
  } catch (e) {
    return m.reply(raraWrap("Panel", `Gagal validasi nomor WhatsApp.`))
  }

  // Access control
  const gcSellerAccess = isGcSeller(m.chat, serverVersion)
  if (!gcSellerAccess && !hasAccessToServer(m.sender, serverVersion, m.isOwner)) {
    const userRole = getUserRole(m.sender, serverVersion)
    return m.reply(
      `AKSES DITOLAK\n\n` +
      `Kamu tidak punya akses ke ${serverVersion.toUpperCase()}\n` +
      `Role kamu: ${userRole || "Tidak ada"}\n\n` +
      `Hubungi admin untuk mendapat akses.`,
      "Panel"
    )
  }

  // Jeda check
  const jedaCheck = checkPanelJeda(m)
  if (!jedaCheck.allowed) {
    return m.reply(jedaCheck.message)
  }

  // Get server config
  const serverConfig = getServerConfig(pteroConfig, serverKey)
  const missingConfig = validateServerConfig(serverConfig)

  if (missingConfig.length > 0) {
    const available = getAvailableServers(pteroConfig)
    return m.reply(raraWrap("Panel",
      `Server ${serverVersion.toUpperCase()} belum dikonfigurasi\n` +
      `Missing: ${missingConfig.join(', ')}\n` +
      `Server tersedia: ${available.join(', ') || 'none'}`
    ))
  }

  // Use custom username from command
  const username = usernameInput.toLowerCase().replace(/[^a-z0-9_]/g, '')
  const email = `${username}@raramultidevice.id`
  const name = capitalize(username) + " Server"
  const password = username + crypto.randomBytes(3).toString("hex")
  const serverLabel = serverVersion.toUpperCase()

  const ramLabel = ramMb === 0 ? "Unlimited" : `${ramMb / 1024} GB`
  const diskLabel = diskMb === 0 ? "Unlimited" : `${diskMb / 1024} GB`

  await m.reply(raraWrap("Panel",
    `Membuat panel ${serverLabel}\n\n` +
    `RAM: ${ramLabel}\n` +
    `Disk: ${diskLabel}\n` +
    `CPU: ${cpu === 0 ? "Unlimited" : cpu + "%"}\n` +
    `Target: ${targetUser.split("@")[0]}`
  ))

  try {
    // Create user
    let userRes
    try {
      userRes = await axios.post(
        `${serverConfig.domain}/api/application/users`,
        { email, username, first_name: name, last_name: "Panel", language: "en", password },
        { headers: { Authorization: `Bearer ${serverConfig.apikey}`, "Content-Type": "application/json", Accept: "Application/vnd.pterodactyl.v1+json" } }
      )
    } catch (e) { e._step = 'create_user'; throw e }

    const user = userRes.data.attributes

    // Fetch egg startup
    let eggRes
    try {
      eggRes = await axios.get(
        `${serverConfig.domain}/api/application/nests/${serverConfig.nestid}/eggs/${serverConfig.egg}`,
        { headers: { Authorization: `Bearer ${serverConfig.apikey}`, "Content-Type": "application/json", Accept: "Application/vnd.pterodactyl.v1+json" } }
      )
    } catch (e) { e._step = 'fetch_egg'; throw e }

    const startupCmd = eggRes.data.attributes.startup

    // Create server with custom specs
    let serverRes
    try {
      serverRes = await axios.post(
        `${serverConfig.domain}/api/application/servers`,
        {
          name,
          description: buildServerDescription(`Created at ${formatDate()} [${serverLabel}] Custom`),
          user: user.id,
          egg: parseInt(serverConfig.egg),
          docker_image: "ghcr.io/parkervcp/yolks:nodejs_18",
          startup: startupCmd,
          environment: { INST: "npm", USER_UPLOAD: "0", AUTO_UPDATE: "0", CMD_RUN: "npm start", JS_FILE: "index.js" },
          limits: { memory: ramMb, swap: 0, disk: diskMb, io: 500, cpu: cpu },
          feature_limits: { databases: 5, backups: 5, allocations: 5 },
          deploy: { locations: [parseInt(serverConfig.location)], dedicated_ip: false, port_range: [] },
        },
        { headers: { Authorization: `Bearer ${serverConfig.apikey}`, "Content-Type": "application/json", Accept: "Application/vnd.pterodactyl.v1+json" } }
      )
    } catch (e) { e._step = 'create_server'; throw e }

    const server = serverRes.data.attributes

    // Auto-generate ptlc_
    let clientApiKey = null
    try {
      clientApiKey = await generateClientApiKey(serverConfig.domain, email, password)
    } catch (e) {
      console.log("[Rara Panel] ptlc_ generation skipped:", e.message)
    }

    // Save ptlc_ to database
    if (clientApiKey) {
      try {
        const db = getDatabase()
        const panelKeys = db.setting('panelClientKeys') || {}
        panelKeys[m.sender] = {
          ptlc: clientApiKey,
          domain: serverConfig.domain,
          serverId: server.id,
          serverLabel: serverLabel,
          username: user.username,
          createdAt: Date.now()
        }
        db.setting('panelClientKeys', panelKeys)
      } catch (e) {
        console.log("[Rara Panel] Failed to save ptlc_ to db:", e.message)
      }
    }

    // Build detail text
    let detailTxt = `PANEL BERHASIL DIBUAT\n\n`
    detailTxt += `Server: *${serverLabel}*\n`
    detailTxt += `Username: *${user.username}*\n`
    detailTxt += `Password: *${password}*\n`
    detailTxt += `RAM: *${ramLabel}*\n`
    detailTxt += `Disk: *${diskLabel}*\n`
    detailTxt += `CPU: *${cpu === 0 ? "Unlimited" : cpu + "%"}*\n`
    detailTxt += `Server ID: *${server.id}*\n`
    detailTxt += `Panel: ${serverConfig.domain}\n`
    if (clientApiKey) {
      detailTxt += `Client Key: *${clientApiKey}*\n`
      detailTxt += `Power control: .startserver .stopserver .restartserver .cekserver\n`
    }
    detailTxt += `\nSimpan data ini, jangan bagikan ke siapapun!`

    const headerMedia = await prepareWAMessageMedia(
      { image: getAssetBuffer("panel-thumb") },
      { upload: sock.waUploadToServer }
    )

    // Baca delivery mode
    const db = getDatabase()
    const deliveryMode = db.setting('panelDeliveryMode') || 1

    function buildPanelMsg(recipient) {
      return generateWAMessageFromContent(
        recipient,
        {
          viewOnceMessage: {
            message: {
              messageContextInfo: { deviceListMetadata: {}, deviceListMetadataVersion: 2 },
              interactiveMessage: proto.Message.InteractiveMessage.fromObject({
                contextInfo: { mentionedJid: [recipient] },
                body: proto.Message.InteractiveMessage.Body.fromObject({ text: detailTxt }),
                footer: proto.Message.InteractiveMessage.Footer.fromObject({ text: `Panel Pterodactyl - ${serverConfig.domain}` }),
                header: proto.Message.InteractiveMessage.Header.fromObject({
                  hasMediaAttachment: true,
                  imageMessage: headerMedia.imageMessage,
                }),
                nativeFlowMessage: proto.Message.InteractiveMessage.NativeFlowMessage.fromObject({
                  buttons: [
                    { name: "cta_copy", buttonParamsJson: JSON.stringify({ display_text: "Copy Username", copy_code: username }) },
                    { name: "cta_copy", buttonParamsJson: JSON.stringify({ display_text: "Copy Password", copy_code: password }) },
                    { name: "cta_url", buttonParamsJson: JSON.stringify({ display_text: "Buka Panel", url: serverConfig.domain }) },
                  ],
                }),
              }),
            },
          },
        },
        {}
      )
    }

    async function sendDetailToChat(chatId) {
      const panelMsg = buildPanelMsg(chatId)
      await sock.relayMessage(chatId, panelMsg.message, { messageId: panelMsg.key.id })
    }

    const confirmTxt = `Panel *${serverLabel}* berhasil dibuat\n\nUntuk: ${targetUser.split("@")[0]}\nRAM: ${ramLabel}\nDisk: ${diskLabel}\nCPU: ${cpu === 0 ? "Unlimited" : cpu + "%"}`

    // Delivery mode
    if (deliveryMode === 1) {
      await sendDetailToChat(m.sender)
      if (targetUser !== m.sender) await sendDetailToChat(targetUser)
      await m.reply(raraWrap("Panel", confirmTxt + "\n\nDetail akun sudah dikirim ke DM kamu"))
    } else if (deliveryMode === 2) {
      await sendDetailToChat(m.chat)
      if (targetUser !== m.sender && targetUser !== m.chat) await sendDetailToChat(targetUser)
    } else if (deliveryMode === 3) {
      await sendDetailToChat(m.sender)
      await sendDetailToChat(m.chat)
      if (targetUser !== m.sender && targetUser !== m.chat) await sendDetailToChat(targetUser)
    }

    await setPanelLastUsed()
  } catch (err) {
    const rawMsg = err?.response?.data?.errors?.[0]?.detail || err?.response?.data?.message || err.message
    const errorMap = {
      'has already been taken': `Username/email *${username}* sudah dipakai, coba lagi`,
      'could not find': 'Egg atau nest tidak ditemukan, cek config',
      'No suitable allocation': 'Tidak ada port tersedia di server',
      'unauthorized': 'API key tidak punya permission',
    }
    const friendly = Object.entries(errorMap).find(([k]) => rawMsg.toLowerCase().includes(k))
    if (isLocationMismatchError(rawMsg)) {
      const help = await buildLocationMismatchHelp(serverConfig);
      if (help) return m.reply(raraWrap("Panel", help));
    }
    return m.reply(raraWrap("Panel", `GAGAL MEMBUAT PANEL\n\n${friendly ? friendly[1] : rawMsg}`))
  }
}

export { pluginConfig as config, handler }
